version: '3'
services:
  # main-gateway:
  #   build:
  #     # dockerfile: ./apps/micro-server/Dockerfile
  #     dockerfile: Dockerfile
  #     context: .
  #     # Only will build development stage from our dockerfile
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/node_modules
  #   env_file:
  #     - .env.development.local
  #     # Run a command against the development stage of the image
  #     # command: yarn prisma migrate dev --name soft-delete --schema=./libs/prisma/prisma/schema.prisma &&  yarn start:dev micro-server
  #   command: yarn start:dev micro-server
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - broker

  # service-1:
  #   # image: micro-server_main-gateway
  #   build:
  #     #   # dockerfile: ./apps/my-app/Dockerfile
  #     dockerfile: Dockerfile
  #     context: .
  #     #   # Only will build development stage from our dockerfile
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - .env.development.local
  #     # Run a command against the development stage of the image
  #   command: yarn start:dev my-app
  #   depends_on:
  #     - broker

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: LISTENER_BOB://0.0.0.0:29092,LISTENER_FRED://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:master
    depends_on:
      - kafka
    ports:
      - 9000:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: LISTENER_BOB://broker:29092

  micro-service-postgres-db:
    image: postgres:14
    restart: unless-stopped
    container_name: micro-service-postgres-db
    env_file:
      - .env.development.local
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
